### ISSUE TITLE
Home page name in breadcrumbs

### ISSUE THREAD

**Issue by wesholing** [eastbaydsa/website#105]
I just noticed the breadcrumbs use the full sentence for the home page as the name of the link.

![screenshot-2018-4-12 east bay dsa socialist school](https://user-images.githubusercontent.com/1048591/38703475-306c9778-3e58-11e8-9cb9-11ea900c8cd2.png)

It also points to `/home-test`. How can we get the text to just read "East Bay DSA" and direct it to the root (not home-test)?

**Comment by dominic** [comment]
This is actually a misuse of pages as they exist today. The home page content is, today, stored at https://eastbaydsa-website-staging.herokuapp.com/admin/homes, and not in a Page object. The long and short is that every page doesn't need to be owned by the home page.

I've pushed an update that includes the home page in all page breadcrumbs, and and hopefully illustrates the problem a little more cleanly in the updated design:
<img width="788" alt="screen shot 2018-04-15 at 1 08 59 am" src="https://user-images.githubusercontent.com/185645/38776305-a09dabf2-4049-11e8-94d8-1d57cceb2d48.png">

**Comment by wesholing** [comment]
Thanks for taking a look at this. I'm still not clear on how it's supposed to work, though. Should I delete the home-test page? And the home page should still be the parent of landing pages (e.g. About, News, Events), right? Typical information architecture puts the home page above the next level of pages, not on the same level.

**Comment by kyleschmolze** [comment]
As of #119, I would like to indeed merge Home into Pages, and this bug won't happen anymore! (breadcrumbs always display the home link, regardless of the final parent, and home subpages show up on the homepage just like any normal page)
